### PR TITLE
Add toggle outline cvar

### PR DESCRIPTION
**Pull request by dch-GH**

### CODE REVIEW

**Comment by PJB3005** [comment]
There is no reason for this cvar to be part of the engine, when content is the only thing that cares about it.

**Comment by dch-GH** [comment]
@PJB3005 Where should I register it in Client? I was having trouble finding the right place to register client cvars.

**Comment by PJB3005** [comment]
`EntryPoint.cs` is a good place to.

**Comment by dch-GH** [comment]
I figured so. Just not seeing any other cvars being registered there put me off. Will do.

**Comment by dch-GH** [comment]
M'kay, https://github.com/space-wizards/space-station-14/pull/1185 should be ready now.

**Pull request closed without merging**
