### PR TITLE
Add BeforeDraw method to Overlay.cs

### PR DESCRIPTION
**Pull request by thedraccx**
Add BeforeDraw method to overlays to allow for necessary setup

### CODE REVIEW

**Comment by PJB3005** [comment]
I'm not seeing the use for this. Couldn't this be done by the code that adds the overlay?

**Comment by thedraccx** [comment]
Well since it's so decoupled at the moment you can't actually get a reference to the overlay you're adding. It's just like ChangeOverlay(enum). So I needed a way to know when the overlay was about to start being drawn so I could properly set the start time, and take a screenshot of the game world.

**Comment by PJB3005** [comment]
That's better solved by fixing the crappy screen effects component content-side, probably?

**Comment by thedraccx** [comment]
Yeah you're right. For some reason I thought that one was also under RobustToolbox. I'll look into that instead

**Pull request closed without merging**
