### PR TITLE
Purge localization manager

### PR DESCRIPTION
**Pull request by DTanxxx**
Removed localization manager dependency from EntitySpawnWindow

### CODE REVIEW

**Comment by exp111** [comment]
Seems like the commits got mixed up.
Are there more _loc usages in the engine you can purge now?

**Comment by DTanxxx** [comment]
I think in the engine there is only EntitySpawnWindow that uses _loc. Would you like me to add LoadCulture method to Loc so that I can use Loc.LoadCulture in the main project solution?

**Comment by exp111** [comment]
Yeah you could do that

**Comment by DTanxxx** [comment]
Just a quick question, in order for the build test to pass, I don’t think I can just remove the _loc parameter from method since wouldn’t that break the main project solution where _loc is actually passed in as an argument? Is there a way to simultaneously commit changes in both projects in one go when they are separate projects?

**Comment by PJB3005** [comment]
Make a new overload of the constructor that doesn't take in a localization manager, flag the old one with `[Obsolete]`, remove it some time later. Way easier than doing simultaneous updates like that.

**Comment by DTanxxx** [comment]
Hi PJB3005,
Does my 'Applied feedback' commit look like what you were looking for? I added [Obsolete] to the old constructor and also added a new one without _loc parameter. However I couldn't find a way to remove the old constructor yet so I might need to wait until this commit becomes merged.

**Review by PJB3005 — CHANGES_REQUESTED** [review]
Don't duplicate the code like that. Have the obsolete constructor just call the new constructor instead.

**Review by PJB3005 — APPROVED** [review]

**Pull request merged**
