### PR TITLE
Change cvar usages to use CVarDef and define them in CVars

### PR DESCRIPTION
**Pull request by DrSmugleaf**
~~Requires https://github.com/space-wizards/RobustToolbox/pull/1329~~

Engine PR of https://github.com/space-wizards/space-station-14/pull/2250

### CODE REVIEW

**Comment by PJB3005** [comment]
@DrSmugleaf tests failing.

**Comment by DrSmugleaf** [comment]
> @DrSmugleaf tests failing.

Fixed, I think its just content tests now.

**Comment by PJB3005** [comment]
Why does this cause content tests to fail, though?

**Comment by DrSmugleaf** [comment]
> Why does this cause content tests to fail, though?

Very good question actually

I'll check tomorrow

**Comment by DrSmugleaf** [comment]
@PJB3005 Fixed, it was from a lack of default value in OnValueChanged and calling RegisterIoC too late in test setup leading to the server assembly not being loaded.

**Comment by PJB3005** [comment]
I'm still seeing test failures.

**Comment by DrSmugleaf** [comment]
> I'm still seeing test failures.

They didn't fail when merging this with its content pr locally, I'll test again

**Comment by DrSmugleaf** [comment]
> I'm still seeing test failures.

Fixed in https://github.com/space-wizards/RobustToolbox/pull/1330/commits/a2ddbd9d99ec85de16ee70c0f02d1bb08bb6b7de
Needs https://github.com/space-wizards/space-station-14/pull/2250 to be merged as well.
image

**Pull request merged**
