### PR TITLE
Enable nullables as errors in Robust

### PR DESCRIPTION
**Pull request by metalgearsloth**
Requires https://github.com/space-wizards/space-station-14/pull/3903

### CODE REVIEW

**Comment by metalgearsloth** [comment]
GITHUB AAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by metalgearsloth** [comment]
Scope has now increased

**Comment by metalgearsloth** [comment]
Tests are gucci 100 locally good to merg

**Review by ZoldorfTheWizard — APPROVED** [review]
Wizardman approves

**Pull request merged**
