### PR TITLE
Automatically unsubscribe event bus registrations in entity system shutdown.

### PR DESCRIPTION
**Pull request by PJB3005**

### CODE REVIEW

**Review by PaulRitter — CHANGES_REQUESTED** [review]
imo the unsubscribe methods should remove subscriptions from the `_subscriptions` list, else you'll have weird behaviour if you unsubscribe manually for whatever reason

**Comment by gradientvera** [comment]
> imo the unsubscribe methods should remove subscriptions from the `_subscriptions` list, else you'll have weird behaviour if you unsubscribe manually for whatever reason

imo, they should remove the subscriptions from the list AND unsubscribe from the event bus.

**Comment by PJB3005** [comment]
I mostly did it like this because the code doesn't explode from a double unregistration, and I don't want to bother synchronizing a submodule update.

We already decided that stuff shouldn't be doing eventbus registations mid-game anyways so I don't think it's a big deal.

**Comment by PaulRitter** [comment]
> > imo the unsubscribe methods should remove subscriptions from the `_subscriptions` list, else you'll have weird behaviour if you unsubscribe manually for whatever reason
> 
> imo, they should remove the subscriptions from the list AND unsubscribe from the event bus.

yes, i meant he should *add* the removal to the unsubscribe methods

**Review by PaulRitter — APPROVED** [review]

**Pull request merged**
