### PR TITLE
Replaces noSprite.png with Gmod Error Sprite

### PR DESCRIPTION
**Pull request by SweptWasTaken**
It's just a nonanimated png right now because I couldn't figure out how to load an rsi with 
`ResourcePath`. 

https://github.com/space-wizards/RobustToolbox/blob/b7f3627ef179c272152b89189002f1b34cc46355/Robust.Client/ResourceManagement/ResourceTypes/TextureResource.cs#L14

I included the animated .rsi if anyone can add to this pr and make it work.

Looks cool doe

### CODE REVIEW

**Comment by PJB3005** [comment]
You can't make it an animated fallback because the whole point is to return a single texture.

**Comment by SweptWasTaken** [comment]
Ok then use the static png then?

**Comment by PJB3005** [comment]
Yes.

I do think I could write some code to make sprite component use this as a animated fallback explicitly (probably a good idea tbh) but making everything use the animated fallback is (sanely) impossible.

**Comment by PJB3005** [comment]
The best part about this is that this made me actually look at failure paths in case of missing RSI/states so the game is significantly less prone to blowing up from these things now.

**Pull request merged**
