### PR TITLE
fix fatal error in DebugConsole.xaml.cs

### PR DESCRIPTION
**Pull request by notquitehadouken**
some stupid bug that prevented me from running client
this fixed it
probably not the best solution but i couldn't find anything wrong with the rest of the code

### CODE REVIEW

**Comment by metalgearsloth** [comment]
Post a stacktrace or use VS or Rider instead.

Also your editor is using tabs not spaces.

**Comment by notquitehadouken** [comment]
> Post a stacktrace or use VS or Rider instead.

stacktrace be here
```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Robust.Client.UserInterface.CustomControls.DebugConsole.<_loadHistoryFromDisk>b__47_0() in C:\Users\ankleboy\hell\space-station-14\RobustToolbox\Robust.Client\UserInterface\CustomControls\DebugConsole.xaml.cs:line 229
   at Robust.Client.UserInterface.CustomControls.DebugConsole._loadHistoryFromDisk() in C:\Users\ankleboy\hell\space-station-14\RobustToolbox\Robust.Client\UserInterface\CustomControls\DebugConsole.xaml.cs:line 195
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Robust.Shared.Asynchronous.RobustSynchronizationContext.ProcessPendingTasks() in C:\Users\ankleboy\hell\space-station-14\RobustToolbox\Robust.Shared\Asynchronous\RobustSynchronizationContext.cs:line 60
   at Robust.Shared.Asynchronous.TaskManager.ProcessPendingTasks() in C:\Users\ankleboy\hell\space-station-14\RobustToolbox\Robust.Shared\Asynchronous\TaskManager.cs:line 28
   at Robust.Client.GameController.Input(FrameEventArgs frameEventArgs) in C:\Users\ankleboy\hell\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.cs:line 569
   at Robust.Client.GameController.<StartupContinue>b__57_2(Object sender, FrameEventArgs args) in C:\Users\ankleboy\hell\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.cs:line 237
   at Robust.Shared.Timing.GameLoop.Run() in C:\Users\ankleboy\hell\space-station-14\RobustToolbox\Robust.Shared\Timing\GameLoop.cs:line 184
   at Robust.Client.GameController.ContinueStartupAndLoop(DisplayMode mode) in C:\Users\ankleboy\hell\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 134
   at Robust.Client.GameController.GameThreadMain(DisplayMode mode) in C:\Users\ankleboy\hell\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 119
   at Robust.Client.GameController.<>c__DisplayClass100_0.<Run>b__0() in C:\Users\ankleboy\hell\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 86
```

> Also your editor is using tabs not spaces.

whoops

**Comment by notquitehadouken** [comment]
me when debug console history consistently fails to load

**Comment by notquitehadouken** [comment]
@metalgearsloth

**Pull request closed without merging**
