### PR TITLE
MapInit ECS event

### PR DESCRIPTION
**Pull request by mirrorcult**
it is what it is

Required for space-wizards/space-station-14#4154

### CODE REVIEW

**Review by gradientvera — APPROVED** [review]
Good ECS PR

**Comment by gradientvera** [comment]
Given the event instance doesn't have any data in it, maybe you can hold an static instance to it somewhere btw, that would reduce allocations and make your code go BRRR

**Comment by mirrorcult** [comment]
addressed review, idk if thats correct or not

**Review by gradientvera — APPROVED** [review]

**Comment by gradientvera** [comment]
aye, that works, good PR

**Pull request merged**
