### PR TITLE
Rewrite the entire lighting architecture on accident (to add normalmaps)

### PR DESCRIPTION
**Pull request by notquitehadouken**
## Lighting be like.

- [ ] Hope that I suddenly learn how to OpenGL
- [x] Weep
- [ ] Do the bare minimum
- [ ] Hope I don't have to

## Normals be like.

- [ ] Put a place for normal maps in RSIs
- [x] Allow loading from file into RSIs
- [x] Have a default normal map (0, 0, 1)
- [ ] Try not to rework the entire lighting engine
- [ ] Do that thing where I painstakingly change every single thing that requires a texture
- [ ] Come up with a better idea than a tuple
- [ ] Make everything use a tuple for textures
- [ ] Make normals actually do stuff with lighting
- [ ] Make sure it actually runs good (probably gonna be fine)

### CODE REVIEW

**Comment by MACMAN2003** [comment]
does this mean it'd be possible to make an unusually spherical circle....

**Comment by PJB3005** [comment]
> Make normals actually do stuff with lighting

Good luck rewriting the entire rendering architecture.

**Comment by PJB3005** [comment]
(I am sarcastic, sorry)

**Comment by PJB3005** [comment]
More productively:

Implementing this will require a complete rewrite of the rendering engine to make it render normals into a separate g-buffer, much like 3D engines. I do not think it is even productive to attempt this on the current shitpile of OpenGL code that is our renderer.

**Comment by moonheart08** [comment]
> More productively:
> 
> Implementing this will require a complete rewrite of the rendering engine to make it render normals into a separate g-buffer, much like 3D engines. I do not think it is even productive to attempt this on the current shitpile of OpenGL code that is our renderer.

Adding atop this, our current rendering approach (Deferred Lighting) is incompatible with normal maps, the lighting engine cannot be used as is. In order to support normals we'd need either a Forward+ (probably the ideal approach) or *actual* Deferred renderer. Our current approach is good due to its simplicity for the number of lights it can handle but that simplicity comes at the cost of advanced lighting effects.

**Comment by notquitehadouken** [comment]
> > More productively:
> > Implementing this will require a complete rewrite of the rendering engine to make it render normals into a separate g-buffer, much like 3D engines. I do not think it is even productive to attempt this on the current shitpile of OpenGL code that is our renderer.
> 
> Adding atop this, our current rendering approach (Deferred Lighting) is incompatible with normal maps, the lighting engine cannot be used as is. In order to support normals we'd need either a Forward+ (probably the ideal approach) or _actual_ Deferred renderer. Our current approach is good due to its simplicity for the number of lights it can handle but that simplicity comes at the cost of advanced lighting effects.

i'll give up once i run out of bullshit to pull

**Comment by deathride58** [comment]
It might genuinely be feasible to fake normal maps by having them offset where exactly in UV space the default shader pulls from the lighting framebuffer, though this could end up being quite janky. But doing it proper is out of the question without some massive changes to rendering as a whole.

**Comment by notquitehadouken** [comment]
image
highlight

**Comment by MACMAN2003** [comment]
if you need any assistance with learning opengl (the hard part) then i highly recommend [https://learnopengl.com](url)

**Comment by notquitehadouken** [comment]
after running in circles repeatedly with putting ( , ) on everything i have given up and will try again once i come up with a better idea

**Comment by notquitehadouken** [comment]
image
i made pi two

**Comment by MACMAN2003** [comment]
pi two?? that's just tau :trollface:

**Comment by deltanedas** [comment]
Activate Windows
Go to Settings to activate Windows.

**Pull request closed without merging**
