### PR TITLE
Fix TryGetController nullability

### PR DESCRIPTION
**Pull request by DrSmugleaf**

### CODE REVIEW

**Review by PJB3005 — APPROVED** [review]

**Comment by PaulRitter** [comment]
you might wanna address those juicy nullability-errors

**Comment by PaulRitter** [comment]
also wont this throw alot of nullability-errors in content? have you built this?

**Comment by DrSmugleaf** [comment]
> also wont this throw alot of nullability-errors in content? have you built this?

It will, content PR is still pending.

**Comment by metalgearsloth** [comment]
@DrSmugleaf is content pr still pending bb

**Comment by Acruid** [comment]
What is going on with this PR. Did the content one ever get made?

**Comment by metalgearsloth** [comment]
Probably being deprecated if physics is ever done so you could close it.

**Comment by DrSmugleaf** [comment]
https://github.com/space-wizards/space-station-14/issues/3083

**Pull request closed without merging**
