### PR TITLE
feat: DrawingHandleScreen now can draw segment of bagel

### PR DESCRIPTION
**Pull request by Fildrance**
To create better UX for radial menu it is required to draw background for radial sectors - added feature for DrawingHandleScreen to do exactly that. To give code more usages also added parameter to draw non-filled segment - it can work as borders.

Sample of what can be done using this changes is in following attachment:

https://github.com/user-attachments/assets/5ddae535-08df-4730-b089-6131956eb2a2

### CODE REVIEW

**Comment by Fildrance** [comment]
Forgot about changelog, gonna add it :(

**Comment by Fildrance** [comment]
Done : )

**Comment by PJB3005** [comment]
Isn't this use case already covered by `HasPoint`? The `PixelRect` check is only if `RectClipContent` is set, and that's *intended* to be a rough-pass optimization only.

**Comment by Fildrance** [comment]
> Isn't this use case already covered by `HasPoint`? The `PixelRect` check is only if `RectClipContent` is set, and that's _intended_ to be a rough-pass optimization only.

Ye sorry it looks like it works with HasPoint. Wierd. I'll repurpose this PR for part that renders bagle segment!

**Comment by Fildrance** [comment]
Sample of how it looks with 'filled = false'
image

**Comment by PJB3005** [comment]
This feels specific enough to just be in content instead.

And please don't re-use PRs like this, make a new one if you must.

**Comment by Fildrance** [comment]
> This feels specific enough to just be in content instead.
> 
> And please don't re-use PRs like this, make a new one if you must.

i will not be able to use stack alloc in Content.Client

**Comment by PJB3005** [comment]
Pre-allocate the buffer, it's a highly specific call it's really not that big of a deal.

**Comment by Fildrance** [comment]
ok

**Pull request closed without merging**
