### PR TITLE
Change netinterp ratio defeault

### PR DESCRIPTION
**Pull request by mirrorcult**

### CODE REVIEW

**Comment by mirrorcult** [comment]
this wouold be in ss14 but no content engine cvar overrides

**Comment by mirrorcult** [comment]
image

you have gotta be eating my ass raw right now

**Comment by ElectroJr** [comment]
Test issues aside, what's the problem with just using `OverrideDefault()` in content?

**Comment by mirrorcult** [comment]
> Test issues aside, what's the problem with just using `OverrideDefault()` in content?

that either didn't exist or pjb was unaware of it cause i asked

image

either way i'll just do it like that

**Pull request closed without merging**
