### PR TITLE
SFML Port Finished

### PR DESCRIPTION
**Pull request by ZoldorfTheWizard**
Summary:
-SFML succesfully ported over, No more Gorgon 
-Cross Platform Achieved, Project can now be built and ran from Windows/Mac/Linux OS 
-http://i.imgur.com/g39jqyt.png

### CODE REVIEW

**Comment by Iamgoofball** [comment]
oh hey I can merge this apparently

**Comment by theOperand** [comment]
IT'S HABBEDING

Seriously though, this is great.
Op 25-mrt.-2015 05:58 schreef "Iamgoofball" notifications@github.com:

**Comment by PJB3005** [comment]
This is amazing!

**Comment by ghost** [comment]
Stuff is happening :D

**Pull request merged**
