### PR TITLE
SFML Merge

### PR DESCRIPTION
**Pull request by YotaXP**
This merges the SFML branch into master. (duh)
**Let the deed be done!**

### CODE REVIEW

**Comment by YotaXP** [comment]
Ignore that first Travis fail.  Accidentally pushed to the main repo and deleted the branch before Travis could snag it.

**Comment by tjohnman** [comment]
This is a momentous occasion.

DO IT!

**Comment by volundr-** [comment]
I'd rather have merged in the other direction first, but YOLO, fuck it

**Comment by johnku1** [comment]
Does this compile properly?

**Comment by tjohnman** [comment]
It does compile.

**Comment by thomasstoeckert** [comment]
I've not been following this too closely, what does SFML do?

**Comment by YotaXP** [comment]
It's a cross-platform rendering lib.  A replacement for Gorgon.

**Pull request merged**
