### PR TITLE
TransformComponent.MapID returns null instead of throwing

### PR DESCRIPTION
**Pull request by DamianX**
Because I need to spawn an entity in nullspace for character preview.
`GridID` also throws currently, should I change that as well even if I don't need it?

### CODE REVIEW

**Comment by PJB3005** [comment]
Making grid ID not throw is probably best yeah.

**Comment by Acruid** [comment]
The only thing this PR does is allow someone to spawn an orphan entity outside of the scene tree. Removing the MapID exception is not a solution to anything. Returning the Nullspace MapID does not make the transform an entity inside the Nullspace scene graph.

The PR is not getting accepted at this point.

**Comment by DamianX** [comment]
I don't know what I need to do.
This allows me to do `entityManager.SpawnEntity("HumanMob_Content", GridCoordinates.Nullspace)`.

**Comment by Acruid** [comment]
That is OK, I will look into a better solution tomorrow.

**Comment by PJB3005** [comment]
image

**Comment by Acruid** [comment]
"Way better fix" is inside https://github.com/space-wizards/RobustToolbox/commit/58d0a771e8882efcfea245fe92485c9a53a96161.

Call `mapMan.CreateNewMapEntity(MapId.Nullspace);` and then spawn entities into MapId.Nullspace like any other map.

**Pull request closed without merging**
