### PR TITLE
Fixed a bug where we assumed the hands were empty before even checking

### PR DESCRIPTION
**Pull request by RednoWCirabrab**

### CODE REVIEW

**Comment by PJB3005** [comment]
Shouldn't you be using phab for this?

**Comment by volundr-** [comment]
Phab is verboten

**Comment by RednoWCirabrab** [comment]
I found Phab to be complicated and there has been little to no activity lately

**Comment by PJB3005** [comment]
Yeah, I asked about it on IRC after this got merged, bye phab

**Pull request merged**
