### PR TITLE
Add option to make `ScrollContainer` return size.

### PR DESCRIPTION
**Pull request by ElectroJr**
Currently a `ScrollContainer` always reports its desired size as zero. Apparently there's a reason for that but it causes issues when you want a control whose size is determined by the size of a `ScrollContainer`. This just adds a `bool` that toggles whether or not it reports its size as zero.

This feature would be nice to have for [space-wizards/space-station-14#4768](https://github.com/space-wizards/space-station-14/pull/4768), which currently just has some janky code to infer the actual desired size of the scroll container.

### CODE REVIEW

**Comment by ShadowCommander** [comment]
The reason why ScrollContainer returns size 0 is so that the parent control can resized without thinking that scroll container is super tall. (e.g. BoxContainer)
@PJB3005 should it be done like this or should it be something like an ActualSize property added somwhere?

**Comment by PJB3005** [comment]
Is this supposed to only be useful when combined with disabling scrolling on one of the axis (so it gets automatic size and no scrolling horizontally, but scrolling vertically)?

**Comment by ElectroJr** [comment]
It should still work if scrolling is enabled on both axes. I just tested by enabling Horizontal scrolling & giving the context menu a MaxWidth, and the scrollbar appears to work fine.


image

Though there are some unrelated issues with text line wrapping, which I never ran  into due to not giving the menu or buttons a MaxWidth, which I probably should do.

**Comment by PJB3005** [comment]
In that case, something else is limiting the available size of the control with a `MaxWidth` or something, so it sounds better to fix the UI layout to simply make the scroll container take up full space top down?

**Comment by ElectroJr** [comment]
So the actual controls involved here are
`Popup` -> `PanelContainer` -> `ScrollContainer` -> `BoxContainer` -> buttons / menu elements

The popup window is supposed to automatically resize in order to be as small as possible, with some upper limit. Without having `ScrollContainer` return its size, I don't know of a neat way of making that work. How do you determine the required size of the popup? I'm still new to the UI stuff, maybe there is an easy solution.

The current work around I've been using in the Popup's `MeasureOverride` is:
1. Get the desired size of the box container
2. If it's larger than the max height, limit it and add the width of the `ScrollContainer`'s vertical scroll bar (which is not publicly accessible, I've just been assuming it's the default width)
3. Get the PanelContainer's `StyleBox` and add the syle size to that to that measurement 
4. Return that as the desired size for the pop-up and open it

I hate that solution and It would be much simpler if the `ScrollContainer` were just able to just report the desired size directly to the `PanelContainer`, which in turn would report to its parent (the popup).

**Comment by ShadowCommander** [comment]
Does the `ScrollContainer` check in your code need `DesiredSize` to be the property checked against or can it be something like a new property `ScrollContainer.ActualSize`?

**Comment by ElectroJr** [comment]
If the `ScrollContainer` stored its desired size in some other property that would help with figuring out the scrollbar width, but AFAIK it would still require me to manually account for the the `PanelContainer`'s stylebox size.

Doing that only takes only a couple of lines of code, so I guess that's an OK solution but It still feels a little bit janky when the scroll container could just optionally report it's size directly to PanelContainer.

**Comment by PJB3005** [comment]
Yeah you're right, this is necessary to be able to handle some scenarios. Looks good then.

**Pull request merged**
