### PR TITLE
Adds overloads for entity system methods with out parameters.

### PR DESCRIPTION
**Pull request by gradientvera**
Okay, I know this seems silly but bear with me here for a second.
This will (imo) improve QOL, as you can use `new WhateverEvent()` in the method calls to raise them, and have it as the return value to do funny pattern matching with.

### CODE REVIEW

**Comment by PJB3005** [comment]
Yeah I really don't like this...

**Comment by RemieRichards** [comment]
Smh she didnt even update the title.

**Comment by gradientvera** [comment]
:pensive:

**Comment by ZoldorfTheWizard** [comment]
instamerging

**Pull request closed without merging**
