### PR TITLE
Obsolete .Owner

### PR DESCRIPTION
**Pull request by metalgearsloth**
If this is something we intend to do to make our engine not run like shit better to avoid the problem getting worse.

### CODE REVIEW

**Comment by moonheart08** [comment]
How does this work with EntityQuery.

**Comment by metalgearsloth** [comment]
Likely EntityQuery would return entityuid as its first arg and the current EntityQuery becomes ComponentQuery without returning the uid.

**Review by DrSmugleaf — APPROVED** [review]
Assuming it doesn't crash the Rider warning view

**Comment by metalgearsloth** [comment]
I'll re-open it soon-ish with the updated API and after bringing down the outstanding prs a bit.

**Pull request merged**
