### PR TITLE
Add HashSet YAML serialization

### PR DESCRIPTION
**Pull request by DrSmugleaf**
Required for https://github.com/space-wizards/space-station-14/pull/2074

### CODE REVIEW

**Comment by RemieRichards** [comment]
consider moment

**Comment by DrSmugleaf** [comment]
> consider moment

dont consider it

**Review by PJB3005 — CHANGES_REQUESTED** [review]
As mentioned on Discord, you should use the `IEnumerable<T>` constructor on `HashSet<T>` instead of doing reflection `Add` calls in the loop like that.

**Comment by DrSmugleaf** [comment]
Reviews addressed.

**Review by PJB3005 — APPROVED** [review]

**Pull request merged**
