### PR TITLE
Replaces all TestFixture constructors with OneTimeSetUp attribute

### LINKED ISSUE #245: Rework unit tests to use proper test fixture attributes.
Currently unit test fixtures are set up by using constructors on `SS14UnitTest`. They should be moved to using `[TestFixtureSetup]` and the alike inside NUnit.

### PR DESCRIPTION
**Pull request by Cyberboss**
Closes #245

Not sure why NUnit.Framework lines were edited, but w/e

### CODE REVIEW

**Comment by PJB3005** [comment]
Did you miss the constructor for the base `SS14UnitTest` or was that intentional?

The changes to the `using` directives were probably the BOM being removed. My guess is your editor isn't listening to the `.editorconfig` file. Wish there was a sane way to tell VS to not use UTF-8-BOM so we could just use UTF-8 like sane people.

The rest looks good though.

**Comment by Cyberboss** [comment]
I'm actually on VS 2017, oddly enough. I'll fix the base constructor as well.

**Comment by PJB3005** [comment]
Actually turns out I'm dumb. The line change was *adding* a BOM, just verified by fetching your branch. We're good there then.

**Review by PJB3005 — APPROVED** [review]

**Comment by PJB3005** [comment]
No idea why neither Travis nor AppVeyor decided to trigger, but I manually checked the PR locally and the tests pass so I'm merging this.

**Comment by ZoldorfTheWizard** [comment]
:+1:

**Pull request merged**
