### PR TITLE
Color.Lerp

### PR DESCRIPTION
**Pull request by TheShuEd**
Linear interpolation function between two colors.

### CODE REVIEW

**Comment by chromiumboy** [comment]
You have to define 't', looks like you named it 'blend' in the input parameters

**Comment by TheShuEd** [comment]
yeah, typo

**Comment by chromiumboy** [comment]
If this is all you need, I approve of the code

However, if you want to get a bit more fancy and avoid the transition to grey in-between the two colors, I've linked [an article on color interpolation](https://www.alanzucconi.com/2016/01/06/colour-interpolation/)

The TLDR is to convert to colors to Hue, Chroma and Lightness before lerpping (the HCY color format in our code, by the looks)

**Comment by TheShuEd** [comment]
Apparently, the correct implementation would be to create ColorHSV, and functions to convert RGB color to HSV, and vice versa.

**Comment by TheShuEd** [comment]
ok, i did it

**Comment by TheShuEd** [comment]
wait, no

**Comment by PJB3005** [comment]
> However, if you want to get a bit more fancy and avoid the transition to grey in-between the two colors, I've linked an article on color interpolation.

Actually this is why you **shouldn't do color math in sRGB space**. There are many ways to interpolate colors depending on the situation but interpolation in sRGB space (99% chance that's what you're doing) is wrong. The article seems to make this exact same mistake given the graphs use sRGB interpolated colors.

**Review by PJB3005 — CHANGES_REQUESTED** [review]
This function really should not be called "lerp" now that it's an HSV-space interpolation. Regardless this is so specific of an operation I'm not sure it makes sense in the engine.

**Comment by TheShuEd** [comment]
check this out. The name is LerpHSV, and it now works correctly.

**Comment by TheShuEd** [comment]
No, it doesn't work. Okay, if it's specific enough, I won't add it here.

**Comment by PJB3005** [comment]
Also we have Color.InterpolateBetween

**Pull request closed without merging**
