### PR TITLE
Adds theyre text macro

### PR DESCRIPTION
**Pull request by lzimann**

### CODE REVIEW

**Comment by ComicIronic** [comment]
There are some tests for the various text macros in `MacroFormatProvider_tests.cs`. It might be a good idea to add tests for this macro as well.

**Comment by Hugal31** [comment]
At some point, if it is interesting for more macros and other languages, I would like to refactor those macros in YAML, so it is easy to add one.

Brain fart of the schema:
```yaml
- name: theyre
  switch:
    on: number
    1:
      switch:
        on: gender
        male: he's
        female: she's
        neuter: it's
        default: they're
    default: they're
```

It might become a whole scripting language though.

**Comment by PJB3005** [comment]
> It might become a whole scripting language though.

My understanding from reading about localization is that it would devolve into that evemtually so I would prefer them staying as C#.

**Comment by RemieRichards** [comment]
why not adopt something like fluent?

**Pull request merged**
