### PR TITLE
Fix a bunch of broken GUI code in relation to the console and chat.

### PR DESCRIPTION
**Pull request by ComicIronic**

### CODE REVIEW

**Comment by ComicIronic** [comment]
@PJB3005 I'm fine with most of the bugfixes, and I would have merged them as individual PRs, so feel free to merge these if you want the changes in ASAP.

**Comment by PJB3005** [comment]
@ComicIronic I don't have merge access.

**Comment by RemieRichards** [comment]
But I do~

though I've not looked at SS14's code in literal years so.

**Comment by PJB3005** [comment]
Quick @Silvertorch5 give me merge access so I can ~~self merge~~ tag issues and PRs.

**Comment by ZoldorfTheWizard** [comment]
>branch conflicts

**Comment by d34d10cc** [comment]
We need this one merged ASAP. @Silvertorch5 You should *really* give PJB merge access.

**Comment by psykzz** [comment]
It still can't be merged with the conflicts, so having write access wouldn't help right now, unless @Silvertorch5 is being slow (which i dont feel like thats the case).

Also if this PR is blocking you, feel free to merge it into your own branches.

**Comment by ZoldorfTheWizard** [comment]
Fixed merge conflict. Merging pr.

**Pull request merged**
