### PR TITLE
Add overlay for physics COM

### PR DESCRIPTION
**Pull request by metalgearsloth**
(Center of mass)

Will be useful whenever I get around to fixing it (tried in the past but was getting weird collision resolution).

### CODE REVIEW

**Comment by gradientvera** [comment]
Nice, screenshots?

**Comment by metalgearsloth** [comment]
image

(Saltern COM is 0,0 because COM is still broken)

**Comment by metalgearsloth** [comment]
(Also drawing circles is slow as so this hammered my framerate)

**Comment by PJB3005** [comment]
Damn I didn't know we have physics Component Object Model.

**Pull request merged**
