### PR TITLE
Use Mono.Net.HttpListener

### PR DESCRIPTION
**Pull request by Tyler-IN**
Please test on platforms...

- [ ] Windows
- [ ] Mac
- [ ] Linux

### CODE REVIEW

**Comment by Tyler-IN** [comment]
Will need a companion for MoMMILink.cs on space-station-14

**Comment by ShadowCommander** [comment]
Works on Windows 10.

**Comment by PJB3005** [comment]
Getting this on Linux:
```
> curl -v localhost:1212/status
*   Trying ::1:1212...
* TCP_NODELAY set
* connect to ::1 port 1212 failed: Connection refused
*   Trying 127.0.0.1:1212...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 1212 (#0)
> GET /status HTTP/1.1
> Host: localhost:1212
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Received HTTP/0.9 when not allowed

* Closing connection 0
curl: (1) Received HTTP/0.9 when not allowed
```

**Comment by TYoung86** [comment]
Closing this, it Mono.Net.HttpListener has problems, is sending "TP/1.1 ..." as part of the response instead of "HTTP/1.1 ..."

Deferring to https://github.com/space-wizards/RobustToolbox/pull/966

**Comment by Tyler-IN** [comment]
Closing this, it Mono.Net.HttpListener has problems, is sending "TP/1.1 ..." as part of the response instead of "HTTP/1.1 ..."

Deferring to https://github.com/space-wizards/RobustToolbox/pull/966

**Pull request closed without merging**
