### PR TITLE
Refactor MSBuild spaghetti, new configurations.

### PR DESCRIPTION
**Pull request by PJB3005**
There is now a "DebugOpt" and "Tools" build configuration available, as discussed on the last maintainer meeting.

Project files and MSBuild stuff has been somewhat cleaned up.

### CODE REVIEW

**Comment by moonheart08** [comment]
Could Release be made to fail on all non-obsolete warnings if I do the fixes?

**Comment by PJB3005** [comment]
Is that a "is it technically possible" or a "should we do this" discussion?

**Comment by moonheart08** [comment]
> Is that a "is it technically possible" or a "should we do this" discussion?

"should we do this", as we discussed prior this would be fine if GHA only (Which I opposed due to local testing of buildability being important), with this people could just build a Tools build if they still have warnings.

**Comment by PJB3005** [comment]
Fine by me, there's little reason to use a release build for anything other than a reference anyways.

**Review by moonheart08 — APPROVED** [review]

**Review by DrSmugleaf — APPROVED** [review]

**Pull request merged**
