### PR TITLE
Shared/ContentPack: Work around a possible bug in PEReader (and/or ILVerify)

### PR DESCRIPTION
**Pull request by Efruit**
`PEReader` (or `ILVerify`) was doing some weird `mmap`ing shit on Linux that caused evil heisenbuggy race condition exceptions during content pack verification. Apparently setting `PEStreamOptions.PrefetchEntireImage` may skip that step. If it isn't actually fixing the issue, at least it slows loading down enough to avoid the race condition.

Disclosure: Since there's no known way to deterministically reproduce the issue, I don't actually know if this fix really works. Consequently, if it does work, I have no clue why.

<details><summary>Spoiler:</summary>
The last attempt at fixing this worked perfectly until I started writing up the PR comment, so maybe this is a good way to repro?
<br/><br/>

**Update:** No luck with reproducing it, maybe the fix actually works?
</details>

If this doesn't work, I'm gating the `Parallel` IL verification parts behind `#if !LINUX` and writing sequential versions. If we get to that point, only the Lord will know if that will work either.

### CODE REVIEW

**Comment by N3X15** [comment]
[`mmap`](https://en.wikipedia.org/wiki/Mmap) is a way of accessing the file without opening the entire thing.  I believe prefetch just loads the entire damn thing into memory so that paging isn't necessary and would probably get around the problem.

**Comment by Efruit** [comment]
> [`mmap`](https://en.wikipedia.org/wiki/Mmap) is a way of accessing the file without opening the entire thing. I believe prefetch just loads the entire damn thing into memory so that paging isn't necessary and would probably get around the problem.

Could be. My current hypothesis on the *how* is that there are [dotnet internals that behave slightly differently with the flag](https://github.com/dotnet/runtime/blob/d1a6945c4ab23b2d621b6e0738d9411409ab8b56/src/libraries/System.Reflection.Metadata/src/System/Reflection/PortableExecutable/PEReader.cs#L28-L33), but yours sounds equally plausible.

There are more details (and a stack trace) on #2130.

**Comment by PJB3005** [comment]
PEReader *does* claim that it is thread safe in the documentation. I'm wondering if we might want to try reporting this on the .NET runtime?

Otherwise if this seems to fix it then no problem merging it for now.

CI failure is unrelated AFAICT.

**Comment by Efruit** [comment]
@PJB3005

> I'm wondering if we might want to try reporting this on the .NET runtime?

Maybe? I don't know how kindly they take to "Our code does something weird, but we don't know why, and we can't make it happen on demand. Good luck!"

>Otherwise if this seems to fix it then no problem merging it for now.

Maybe it's just me, but I know I'd feel better about this if someone else could try to repro with and without the patch.

**Comment by PJB3005** [comment]
I'll try a brute force stress test on my server tonight and then file a bug report on dotnet/runtime.

**Comment by gradientvera** [comment]
> I'll try a brute force stress test on my server tonight and then file a bug report on dotnet/runtime.

Did you end up doing this in the end btw? @PJB3005

**Comment by Efruit** [comment]
After additional testing, I was still able to repro with the patch.

In light of that, I'm closing the PR.

**Pull request closed without merging**
