### PR TITLE
Add timestamps to console logs

### PR DESCRIPTION
**Pull request by Cyberboss**
```
    2023-12-20T13:06:55.7153494-05:00 [DEBG] opendream: Finished world topic #4
    2023-12-20T13:06:55.7153948-05:00 [DEBG] opendream: World Topic #5: '127.0.0.1' -> 'tgs_data=%7b%22commandType%22%3a1%2c%22eventNotification%22%3a%7b%22type%22%3a14%2c%22parameters%22%3a%5b%5d%7d%2c%22accessIdentifier%22%3a%22J%2b2OryrzD6ykYSaMlYgzrTx3P14DbXwlBcZeHtn1%22%7d'
    2023-12-20T13:06:55.7154238-05:00 [INFO] world.log: Topic (sleep_offline: 0): tgs_data=%7b%22commandType%22%3a1%2c%22eventNotification%22%3a%7b%22type%22%3a14%2c%22parameters%22%3a%5b%5d%7d%2c%22accessIdentifier%22%3a%22J%2b2OryrzD6ykYSaMlYgzrTx3P14DbXwlBcZeHtn1%22%7d
    2023-12-20T13:06:55.7154302-05:00 [INFO] world.log: TGS DEBUG: OnTopic()
    2023-12-20T13:06:55.7154330-05:00 [INFO] world.log: TGS DEBUG: RequireInitialBridgeResponse()
    2023-12-20T13:06:55.7154350-05:00 [INFO] world.log: TGS DEBUG: RequireInitialBridgeResponse: Passed
    2023-12-20T13:06:55.7154368-05:00 [INFO] world.log: TGS DEBUG: OnTopic passed bridge request gate
    2023-12-20T13:06:55.7154572-05:00 [INFO] world.log: TGS DEBUG: ProcessTopicJson(..., 1)
    2023-12-20T13:06:55.7154626-05:00 [INFO] world.log: TGS DEBUG: ProcessRawTopic(..., 1)
    2023-12-20T13:06:55.7154930-05:00 [INFO] world.log: TGS DEBUG: ProcessTopicCommand(1, ...)
    2023-12-20T13:06:55.7155284-05:00 [INFO] world.log: TGS DEBUG: RequireInitialBridgeResponse()
    2023-12-20T13:06:55.7155306-05:00 [INFO] world.log: TGS DEBUG: RequireInitialBridgeResponse: Passed
    2023-12-20T13:06:55.7155599-05:00 [INFO] world.log: Response (sleep_offline: 0): {"chatResponses":[{"text":"Received event: `[14]`","embed":null,"channelIds":["1"]}]}
    2023-12-20T13:06:55.7158361-05:00 [DEBG] opendream: Finished world topic #5
    2023-12-20T13:06:58.7549901-05:00 [INFO] world.log: TGS DEBUG: RequireInitialBridgeResponse()
    2023-12-20T13:06:58.7549971-05:00 [INFO] world.log: TGS DEBUG: RequireInitialBridgeResponse: Passed
    2023-12-20T13:06:58.8560624-05:00 [INFO] world.log: TGS DEBUG: RequireInitialBridgeResponse()
    2023-12-20T13:06:58.8560681-05:00 [INFO] world.log: TGS DEBUG: RequireInitialBridgeResponse: Passed
    2023-12-20T13:07:25.8263784-05:00 [INFO] statushost.http: POST /shutdown from [::1]:61898
    2023-12-20T13:07:25.8348070-05:00 [INFO] srv: TGS Watchdog Request, shutting down...
```

### CODE REVIEW

**Review by DrSmugleaf — COMMENTED** [review]
At least for the watchdog this would make the logs messy to read, as those already include the timestamp. 
As an example:
```
Dec 21 03:07:51 lizard.spacestation14.io SS14.Watchdog: [DEBG] admin.logs: Saving 3 admin logs.
```
I'm not sure what PJB would prefer.
@PJB3005

**Comment by Cyberboss** [comment]
Kinda odd to generate the timestamp on the parent process as it can drift if there is input delay (GH Actions Windows runners are NOTORIOUS for doing this).

**Review by PJB3005 — CHANGES_REQUESTED** [review]
Yeah this 100% needs to be optional, otherwise journalctl logs are going to be completely unreadable.

**Comment by PJB3005** [comment]
Stale

**Pull request closed without merging**
