### PR TITLE
TryFindComponentOnEntityContainerOrParent no fail please

### PR DESCRIPTION
**Pull request by IProduceWidgets**
TryFindComponentOnEntityContainerOrParent
would fail trying to Resolve on parents that don't have the component its searching for. This prevents that by changing the Resolve to TryComp.

### CODE REVIEW

**Comment by ElectroJr** [comment]
Isn't the trycomp just equivalent to the old resolve? Unless people are passing in components via the ref? I have no idea why this method even takes in a ref comp

**Comment by deltanedas** [comment]
yeah shouldnt foundComponent be out instead of ref

**Comment by IProduceWidgets** [comment]
Agreed, I switched it to out and tested that it works recursively as expected.

Fortunately I think I'm the only person who has tried to use this on content so there's nothing to fix!

**Comment by IProduceWidgets** [comment]
> Isn't the trycomp just equivalent to the old resolve? Unless people are passing in components via the ref? I have no idea why this method even takes in a ref comp

I have no idea why it was using ref. I don't think there's any uses of the method on content, probably because of its scrungliness, and the method that returns all found parent components instead of the first one doesn't use ref and also uses trycomp instead. As for if they're functionally different, the resolve throws an assert if any of the parents while recursing **don't** have the component, which is no good here. Also as ref it required you to pass a ref, which is not needed imo, and unintuitive.

**Comment by IProduceWidgets** [comment]
Bump.
It's just a bugfix, not new functionality.

**Review by PJB3005 — CHANGES_REQUESTED** [review]
This is a minor breaking change which I'd rather not merge. I do get that `out` makes more sense but what's done is done, it should be possible to implement the function regardless.

**Comment by IProduceWidgets** [comment]
Hokay, made it ref again to avoid the breaky.

**Comment by IProduceWidgets** [comment]
Bump

**Review by PJB3005 — APPROVED** [review]

**Pull request merged**
