### PR TITLE
Viewport

### PR DESCRIPTION
**Pull request by patrikturi**
1st commit Is a something that went wrong in my previous commits
2nd commit - MapUtil was awkward, I guess this is how stuff is meant to be used?

``` C#
IoCManager.Resolve<IMapManager>().TileSize
```

### CODE REVIEW

**Comment by PJB3005** [comment]
# HOLY

# SHIT

**Comment by theOperand** [comment]
_Dimitri gestures!_
_Space Station 14 shudders and begins to move!_

**Comment by volundr-** [comment]
Dmitri - can you rebase onto my PR branch and open a PR to silvertorch5? https://github.com/Silvertorch5/space-station-14/pull/19

**Comment by Heredth** [comment]
DOING GOD'S WORK

**Comment by patrikturi** [comment]
@volundr Yes, I was a bit confused whether I should open PR on space-wizzards or on Silvertorch's repo. Also I can push to Silvertorch directly.

**Comment by YotaXP** [comment]
Closing this since the master branch is more or less discontinued.

**Pull request closed without merging**
