### PR TITLE
FixClipping() now check if entity is deleted (bug fix)

### PR DESCRIPTION
**Pull request by komunre**
I need this fix because when flashbangs broke the window into space it cause error because decompression destroys grenade.

FixClipping was trying to move null parent at 0, 0 position.

### CODE REVIEW

**Review by PJB3005 — COMMENTED** [review]
Shouldn't the code *calling* `CanMove()` in this instance be checking if it's deletes?

**Comment by komunre** [comment]
@PJB3005 `CanMove()` Called by `SharedPhysicsSystem` and `PhysicsManager` code in context of checking collided items. I don't think Entity will check itself for moving possibility (anyways, what's wrong?). If you asking what `Owner.Deleted` do - then no. It get owner of `PhysicsComponent` so it's entity with attached component.

Also i tested it on my clusterbang item.

**Comment by metalgearsloth** [comment]
> 
> 
> Shouldn't the code _calling_ `CanMove()` in this instance be checking if it's deletes?

Yes. CanMove actually used to check for Deleted and I removed it for this reason as CanMove is called in a lot of places and not all of them care.

**Comment by komunre** [comment]
So should i add Deleted check in FixCollide instead? By the way why we need to move deleted objects?

**Comment by metalgearsloth** [comment]
If they're deleted as part of collision behaviors it can happen.

It should probably be checked under the part of SimulateWorld that's calling FixClipping. This is me speculating without debugging it myself where I'd be able to give you a concrete answer.

**Comment by komunre** [comment]
nice, i accidentally deleted branch. Now i need to create master branch PR?

**Comment by komunre** [comment]
I removed Delete check from CanMove and added it to the FixClipping (I always was saying it wrong).

**Review by PJB3005 — APPROVED** [review]
Seems good. @metalgearsloth ?

**Review by metalgearsloth — APPROVED** [review]

**Pull request merged**
