### PR TITLE
OnDropdownHide

### PR DESCRIPTION
**Pull request by ImRenQ**
Adds an event that allows the external code to know about the closing of the drop-down list

### CODE REVIEW

**Comment by PJB3005** [comment]
Just curious: what's your use case for this?

**Comment by ImRenQ** [comment]
> Just curious: what's your use case for this?

I need to know when a popup is closed or open

I have a ListContainer, one of the entries contains an OptionButton. When the ListContainer is updated, the open popup is closed. 
Skip ListContainer updates if the popup is open (and updating after it closes) is one solution to this problem

изображение

**Comment by PJB3005** [comment]
That use case would be better served by not rebuilding the entire control tree on update, which is more efficient anyways.

**Comment by ImRenQ** [comment]
ListContainer can't work any other way, as far as I understand

**Comment by PJB3005** [comment]
That is an issue with `ListContainer` that should be solved in content, and even then your use case does not seem appropriate for the control.

**Comment by ImRenQ** [comment]
> That is an issue with `ListContainer` that should be solved in content, and even then your use case does not seem appropriate for the control.

Thanks for explaining this, I'll try to create a new "ListContainer"

**Pull request closed without merging**
