### PR TITLE
Add NoRenderInWorldComponent

### PR DESCRIPTION
**Pull request by notquitehadouken**
for making objects not render in the world

### CODE REVIEW

**Comment by PJB3005** [comment]
Why not just set the sprite to be invisible?

**Comment by notquitehadouken** [comment]
> Why not just set the sprite to be invisible?

that is because i do not know how to do that

**Comment by PJB3005** [comment]
https://github.com/space-wizards/RobustToolbox/blob/0f97f366a6f5494fc4ca32918ab512a0ff24a73f/Robust.Client/GameObjects/Components/Renderable/SpriteComponent.cs#L66

**Comment by notquitehadouken** [comment]
> https://github.com/space-wizards/RobustToolbox/blob/0f97f366a6f5494fc4ca32918ab512a0ff24a73f/Robust.Client/GameObjects/Components/Renderable/SpriteComponent.cs#L66

thank you for your kindness

**Pull request closed without merging**
