### PR TITLE
Medical System: Basic system of External and Internal Organs

### PR DESCRIPTION
**Pull request by RednoWCirabrab**
I have created a basic system representing the External and Internal organs, external represents something like an arm, or the torso, and internal being brain, heart, lungs, etc. The next step would be to implement damaging the organs and having them evaluated when considering the health of the player/mob

### CODE REVIEW

**Comment by ghost** [comment]
:D :+1: 
Needs liver.

**Comment by RednoWCirabrab** [comment]
Done

**Comment by ghost** [comment]
I was mostly joking because alcohol and liver failing.

**Comment by RednoWCirabrab** [comment]
it will be necessary eventually, no reason not to add it :D

**Comment by Heredth** [comment]
You forgot the butt.

**Comment by RednoWCirabrab** [comment]
Nahhh lol

**Comment by ghost** [comment]
When is this going to be merged?

**Comment by RednoWCirabrab** [comment]
Good question, I'll ask

**Comment by ghost** [comment]
@volundr-  ?

**Comment by as334** [comment]
Apparently I have merge access, so i can do it if you want?

**Comment by ghost** [comment]
I don't personally see why not, do you @RednoWCirabrab ?

**Comment by as334** [comment]
yolo

**Comment by RednoWCirabrab** [comment]
Thanks @as334 :+1:

**Pull request merged**
