### PR TITLE
Add component references for SpriteComponent

### PR DESCRIPTION
**Pull request by DrSmugleaf**
Required for https://github.com/space-wizards/space-station-14/pull/2074

### CODE REVIEW

**Review by PJB3005 — COMMENTED** [review]
This doesn't actually work. `[ComponentReference]` is only evaluated for components that also have `[RegisterComponent]`, which these don't (they're still registered via the component factory constructor).

**Review by PJB3005 — COMMENTED** [review]
The engine currently does not actually run component auto-registrations itself so I would prefer if we kept engine components manually registered for now. That or make the engine properly use autoreg.

**Comment by DrSmugleaf** [comment]
> The engine currently does not actually run component auto-registrations itself so I would prefer if we kept engine components manually registered for now. That or make the engine properly use autoreg.

I fixed it for the failing test with https://github.com/space-wizards/RobustToolbox/pull/1303/commits/6d6b9dedd06db4aa91caefd06ec27821846813af, should it be fixed in another way? Or should I just add the server ISpriteRenderableComponent component reference through EntryPoint as it was done for the client and ISpriteComponent before?

**Comment by PJB3005** [comment]
Yes just go back to the manual `Register<>()` calls in the constructor of the component factory like before.

**Comment by DrSmugleaf** [comment]
> Yes just go back to the manual `Register<>()` calls in the constructor of the component factory like before.

Done.

**Pull request merged**
