### PR TITLE
Colour batch reduction

### PR DESCRIPTION
**Pull request by 20kdc**
This reduces the amount of batches created on consecutive `DrawLine` calls with different colours, and allows specifying per-vertex colours to `DrawPrimitives`.

I've also moved out some convenience stuff that was in Clyde when it really didn't need to be (converters for the less complex DrawPrimitives APIs, specifically).

Note that this increases the amount of `stackalloc`s performed by existing uses of DrawPrimitives because they have to convert to the new vertex format.

The advantages are:
+ DrawPrimitives doesn't happen enough for the compatibility wrappers to be a concern
+ this doesn't break Content or OpenDream\*
+ If you're doing anything which involves a lot of colour-switching, this will massively reduce the amount of draw calls you have to deal with

\* OpenDream not tested.

I also fixed a bug in UserInterfaceManager that I don't think anyone's encountered yet.

### CODE REVIEW

**Comment by moonheart08** [comment]
thank fuck.

**Review by PJB3005 — APPROVED** [review]

**Comment by 20kdc** [comment]
did a change happen to UserInterfaceManager?
... will fix this PR, please hold

**Comment by 20kdc** [comment]
Uuuuh PJB did you have to fix any merge conflicts manually?

**Comment by PJB3005** [comment]
Uhhhh, oops

**Comment by 20kdc** [comment]
I'm fixing it dw

**Comment by 20kdc** [comment]
Merge fixed, waiting for CI tests

**Pull request merged**
