### PR TITLE
Godot

### PR DESCRIPTION
**Pull request by PJB3005**

### CODE REVIEW

**Comment by ZoldorfTheWizard** [comment]
@PJB3005 Conflicts pls fix

**Comment by PJB3005** [comment]
So this is pretty much ready to go but there's on gaping elephant in the room: debugging the client doesn't work on Windows. See https://github.com/godotengine/godot/issues/14822

So uh... do we do this or what?

**Comment by SaphireLattice** [comment]
Hooray!

Someone mark this day in the calendar.

**Comment by theOperand** [comment]
:godot: :wakemeup:

**Pull request merged**
