### PR TITLE
Adds default config for diagonal movement setting

### PR DESCRIPTION
**Pull request by CakeQ**
Shouldn't change anything beyond making the configuration option more apparent

### CODE REVIEW

**Comment by PJB3005** [comment]
Personally I'd rather this file be deleted and a default generated automatically by the engine for reference purposes like this. It's a constant source of pain of this file going out of sync.

**Comment by io-june** [comment]
>Personally I'd rather this file be deleted and a default generated automatically by the engine for reference purposes like this. It's a constant source of pain of this file going out of sync.

that would require server host to compile from source code

**Comment by PJB3005** [comment]
> that would require server host to compile from source code

1. no it wouldn't.
2. this would be a problem how?

**Comment by CakeQ** [comment]
Surely you're asking me to do something out of scope? Unless someone plans on writing this supposed automatic config maker the config toml should either include all existing configurations or not exist at all

**Comment by PJB3005** [comment]
I'd rather not merge content-specific cvars into the engine for obvious reasons. I was proposing an alternative method to solve the problem that's content-agnostic.

**Comment by PJB3005** [comment]
Actually it turns out the `saveconfig` command already dumps default config entries. To auto generate the config file you can just run `saveconfig` in the server console.

**Comment by Acruid** [comment]
I'm closing this, it would be better if the toml files were completely removed from the project. You can generate the default ones at any time with `saveconfig` in the console, or somebody improve it by generating default files if they are missing on startup.

**Pull request closed without merging**
