### PR TITLE
More Batch in This Patch

### PR DESCRIPTION
**Pull request by Serkket**
More a u t o m a t i o n

### CODE REVIEW

**Comment by ghost** [comment]
there must be an issue with default python being 2
python3 is safe

**Review by PJB3005 — CHANGES_REQUESTED** [review]
Use `py -3` instead.

**Comment by psykzz** [comment]
Instead of `py -3` add the shebang `#!/usr/local/bin/python python3` which should work universally.

`py` is a windows python launcher, and will be able to read and understand the shebang and run it via python3 if its installed.

**Comment by PJB3005** [comment]
That still won't work if you invoke python directly, like this PR is doing.

**Comment by psykzz** [comment]
Ah your right, for windows to use the shebang you need to use `py` so might as well just do `py -3`

**Comment by ZoldorfTheWizard** [comment]
Please update and create a new pull request.

**Pull request closed without merging**
