### PR TITLE
LoadFromDocument properly detects duplicate entities

### LINKED ISSUE #3079: serv3 doesn't error on duplicate prototype IDs
SS14 has several that have gone unnoticed, the most recent one is BoxSurvival.

### PR DESCRIPTION
**Pull request by Mervill**
I circled back around to this and discovered that the fix is (probably?) easy.

Closes #3079

I tested this locally but I'm pushing the change via the web editor so I don't have to go to the trouble of setting up a Robust fork of my own.

### CODE REVIEW

**Comment by Mervill** [comment]
I should point out that this only works because `_prototypeResults` is never cleared (i.e. after `ResolveResults()`) so as long as that's intended then this is good. (It _is_ cleared when the whole manager is reset)

**Comment by Mervill** [comment]
The content test is failing because it's detecting the duplicates discussed in the content pr

mb1jxrc806141

**Comment by PaulRitter** [comment]
> I should point out that this only works because `_prototypeResults` is never cleared (i.e. after `ResolveResults()`) so as long as that's intended then this is good. (It _is_ cleared when the whole manager is reset)

yep, its intended

**Review by PaulRitter — APPROVED** [review]
good catch!

**Comment by PaulRitter** [comment]
to elaborate, because im not at my phone anymore: yep, prototyperesults dont get cleared because we are pushing composition (inheritance) using the datanodes. Because of hotreloading, we need to keep the mappings around so we can properly push composition again when a prototype gets new mappings. now that i think of it, we could probably make it clear them in release after ResolveResults runs to free up alot of memory. Another quick and easy pr i suppose :D

**Pull request merged**
