### PR TITLE
nests test outputs

### PR DESCRIPTION
**Pull request by PaulRitter**
making the pr to see if i didn't fuck up the enviroment variable check

### CODE REVIEW

**Comment by PaulRitter** [comment]
why tf are tests failing man? prob need to merge master dont i?

**Comment by PJB3005** [comment]
Does this even work correctly with parallelized threads? Does NUnit make sure to avoid mixing their output?

**Comment by PaulRitter** [comment]
> Does this even work correctly with parallelized threads? Does NUnit make sure to avoid mixing their output?

it does not, its very janky. but parallelized threads also shit out their outputs in parallel anyways, so i just went fuck it. that being said, the main usecase for this are integrationtests that dont use parallelization anyways, r-r-right?

**Comment by PJB3005** [comment]
> the main usecase for this are integrationtests that dont use parallelization anyways, r-r-right?

Integration tests are always threaded.

**Comment by PaulRitter** [comment]
> > the main usecase for this are integrationtests that dont use parallelization anyways, r-r-right?
> 
> Integration tests are always threaded.

welp, i ran integration tests locally and it looked fine. only looked weird with the unittests, but those dont produce any output anyways afaict.

**Comment by PaulRitter** [comment]
@PJB3005 see: https://github.com/space-wizards/RobustToolbox/runs/3918868201?check_suite_focus=true

**Comment by PJB3005** [comment]
image

I don't know what to tell you but this looks extremely broken.

**Comment by PaulRitter** [comment]
> image
> 
> I don't know what to tell you but this looks extremely broken.

expand the things and see that there is literally no output there. if those tests were to ever even output text, it would look just as broken.

check the integration tests, thats what this is for. you are looking at the unittests

**Comment by DrSmugleaf** [comment]
Hello I'm here to ask does this work with pooling because if not I'm definitely not fixing it after the fact

**Comment by PJB3005** [comment]
> check the integration tests, thats what this is for. you are looking at the unittests

Then why are empty groups being emitted for unit tests? Why doesn't the group name show the test name? 

*Why* shouldn't this be a thing with unit tests? They can also have output.

**Comment by PaulRitter** [comment]
> Then why are empty groups being emitted for unit tests? Why doesn't the group name show the test name?

because that makes it infinitely hard / i havent found a way to easily add that. wyci

**Comment by Acruid** [comment]
Closed for inactivity.

**Pull request closed without merging**
