### PR TITLE
Fix all warnings

### PR DESCRIPTION
**Pull request by Visne**
Did some cleanup while I was there.

### CODE REVIEW

**Comment by PaulRitter** [comment]
brave touching the dynamictree

**Comment by Visne** [comment]
If I did everything correctly, which might not be true, that stuff is all unused

**Comment by PJB3005** [comment]
I'm still gonna wait on a review from @metalgearsloth just in case.

**Comment by metalgearsloth** [comment]
Okay I double-checked and it was used for the old movebuffer like I thought (UpdatePairs). This got nuked because I had to rewrite it to make shuttles work so it's okay to remove, I just didn't cull it at the time.

**Pull request merged**
