### PR TITLE
Obsolete comp references

### PR DESCRIPTION
**Pull request by metalgearsloth**
Mum sloth is obsoleting code again.

The performance cost of basic component add / removal operations is not worth this.

### CODE REVIEW

**Comment by mirrorcult** [comment]
also we will probably need this dead for arch anyway

**Comment by metalgearsloth** [comment]
Yeah we do I was talking to smug a bit about it.

I realise getcomp / trygetcomp at least don't need it so I can prototype pvs reversion before arch.

**Comment by DrSmugleaf** [comment]
image

**Comment by ElectroJr** [comment]
This shouldn't be obsoleted until we have a replacement for server/client components that inherit from shared components. Because currently people still **need** to use it for that.

**Comment by EmoGarbage404** [comment]
The main uses right now are just:
- gasmixture (should be in shared
- textures (honestly not a clue)

**Comment by ElectroJr** [comment]
Is the plan to just forbit shared comp inheritance?

**Comment by DrSmugleaf** [comment]
> Is the plan to just forbit shared comp inheritance?

With struct components you wouldn't be able to do it anyway. For those that really need it, you can put whatever data in a separate component, which is less expensive with archetypes.

**Pull request merged**
