### PR TITLE
Check if Zstd is installed

### PR DESCRIPTION
**Pull request by wrexbe**
Checks if Zstd is installed, and stops the startup if it isn't, with a fatal log.

### CODE REVIEW

**Comment by PJB3005** [comment]
What prompted this?

**Comment by wrexbe** [comment]
Not having Zstd on my machine

**Comment by PJB3005** [comment]
> Not having Zstd on my machine

What? The game ships zstd itself. Are you on ARM?

**Comment by wrexbe** [comment]
Yes, my computer is Arm :)

**Comment by PJB3005** [comment]
We don't currently officially support ARM. This isn't the only binary you're going to have issues with, so this PR makes no sense. We do not want to encourage people to rely on system packages.

**Comment by wrexbe** [comment]
Alright

**Pull request closed without merging**
