### PR TITLE
Grid line enumerator

### PR DESCRIPTION
**Pull request by Macoron**
Added grid line enumerator. Used for radiation system, but might be used for other purposes.

It use bresenhams line algorithm and wrapped into struct enumerator. Should be fast enough.

### CODE REVIEW

**Comment by PJB3005** [comment]
Do we really want this in engine, or should this go in content or something?

**Comment by Macoron** [comment]
> Do we really want this in engine, or should this go in content or something?

Well, it's possible that some other project that using robust could use draw line algorithm. Though they also probably will want to modify it for they needs.

So it's up to maintainers to decide. I'm ok with both options.

**Comment by metalgearsloth** [comment]
Personally I think it should be alongside the other grid tile methods like GetTilesIntersecting as some other game may want linecasts on tiles.

**Comment by moonheart08** [comment]
Frankly, keep it in this form and then add something atop it specialized for grids.
This is itself really useful. (and saves me from having to memorize the line algorithm every time i need it aaaa)

**Review by ElectroJr — APPROVED** [review]

**Pull request merged**
