### PR TITLE
Open window size fix

### PR DESCRIPTION
**Pull request by wrexbe**
Fix a bunch of UI sizing issues with this one simple trick.

### CODE REVIEW

**Comment by PJB3005** [comment]
What are the bugs fixed by this?

**Comment by wrexbe** [comment]
Because it locks the setsize to desiredsize it breaks ui scaling.

**Comment by PJB3005** [comment]
How is this related to UI scaling? These sizes are all in virtual pixel units.

**Comment by wrexbe** [comment]
Set size clamps the max width and height for the window. So whenever it measures the window it will never let it get bigger again, even if it needs it. The windows figure out their size just fine without this line, so bugs went away, and I didn't see any new ones happen. Mainly noticed this on the sandbox and option window, which were getting cutoff sometimes.

**Pull request merged**
