### PR TITLE
Editorconfig, fixing mistakes from Xamarin and VS

### PR DESCRIPTION
**Pull request by ComicIronic**

### CODE REVIEW

**Comment by psykzz** [comment]
@ComicIronic Conflicts

**Comment by ZoldorfTheWizard** [comment]
You can remove texturevisualizer

**Comment by ComicIronic** [comment]
Done.

**Review by PJB3005 — APPROVED** [review]

**Comment by PJB3005** [comment]
Oh great that doesn't restart Travis.

**Comment by ZoldorfTheWizard** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/space-wizards/space-station-14/pull-request/98/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=space-wizards/space-station-14)

**Pull request merged**
