### PR TITLE
broadphase cleanup

### PR DESCRIPTION
**Pull request by metalgearsloth**
Was I high when I wrote this idk

### CODE REVIEW

**Review by PJB3005 — CHANGES_REQUESTED** [review]
Why change those queues to stacks? Do they actually have to be processed in reverse order like that?

**Comment by metalgearsloth** [comment]
Technically no but there is a hashset checking if an update is already processed (this is mainly useful when changing directions so you don't process both RotateEvent and MoveEvent) so if multiple MoveEvents are queued we only care about the latest.

**Comment by PJB3005** [comment]
Yeah but you're not actively removing those duplicated events from the stack in any way, so you still have to go through the entire thing either way, no?

**Comment by metalgearsloth** [comment]
That is true but it's more about making sure the latest position is used. (I also just realised I'm getting WorldPosition again in SynchronizeFixtures which is really stupid so I also need to fix that).

**Comment by PJB3005** [comment]
As far as I can tell you're using both the new and old position in the move event to calculate displacement (this is for CCD, right?). But wouldn't using the newest event mean you only catch part of the displacement?

it seems like going from oldest, and then just pulling the position off the transform instead of the event, would be better. No?

**Comment by metalgearsloth** [comment]
You're right; I'll come back to this when I port the TOI solver which will be a while so I'll close this for now.

**Pull request closed without merging**
