### PR TITLE
Serialization v3 aka constant suffering

### PR DESCRIPTION
**Pull request by PaulRitter**
Requires https://github.com/space-wizards/space-station-14/pull/3491

[WIP hackmd doc](https://hackmd.io/@ss14/serialization)

### CODE REVIEW

**Review by PaulRitter — COMMENTED** [review]
this code is perfect

**Comment by DrSmugleaf** [comment]
[WIP hackmd doc](https://hackmd.io/@ss14/serialization)

**Review by metalgearsloth — APPROVED** [review]

**Review by gradientvera — APPROVED** [review]
The code is perfect.

**Comment by Acruid** [comment]
The green check mark means it's bug free, SO LETS DO THIS!

**Pull request merged**
