### PR TITLE
added global emote CVars

### PR DESCRIPTION
**Pull request by Nettingman**
Added CVar settings for user defined custom emotes.
Requirement of other PR.

### CODE REVIEW

**Comment by PJB3005** [comment]
Why is this in its own PR?

**Comment by Nettingman** [comment]
Isn't it how I should submit them?
PRs with engine changes page says it should be submitted first and then referenced in the main PR:
https://docs.spacestation14.com/en/general-development/tips/prs-with-engine-changes.html

Sorry this is my first PR with engine change, I may have misunderstood something.

**Comment by PJB3005** [comment]
I didn't realize this is in Robust, which begs the next question: why is this in Robust?

**Comment by Nettingman** [comment]
Because it's a new CVar. I was following the pattern of other user settings which all had their own CVars.

**Comment by PJB3005** [comment]
You can define the new CVars in content with `CCVars.cs`.

**Comment by Nettingman** [comment]
Oh damn, I see. Thank you. This can be closed then.

**Pull request closed without merging**
