### PR TITLE
Disconnect when quitting

### LINKED ISSUE #156: Clean up connections when a client disconnects
When you disconnect from a server, the resource is not cleaned up.

### PR DESCRIPTION
**Pull request by psykzz**
Closes #156 
Close connections when the client clicks `quit`.

### CODE REVIEW

**Review by PJB3005 — APPROVED** [review]
Won't clear when a client gets killed incorrectly but better than nothing.

**Comment by ComicIronic** [comment]
What are we going to do if the client does get killed incorrectly? Have the server try and ping it and kill the connection after a certain number of failures?

**Comment by psykzz** [comment]
I was working on that last night, 
I was keeping track of messages from the client and if the client doesn't send a message within a timeout, we manually disconnect them.

The only issue im having at the moment is if you connect multiple times from the same address, the disconnect kills all the clients. So im fixing that before i do a pull request for it.

**Comment by psykzz** [comment]
@ComicIronic for how i was planning to deal with connections that need to be cleaned up i pushed that to this PR - https://github.com/space-wizards/space-station-14/pull/158

**Comment by psykzz** [comment]
Closing this one in favor of #158

**Pull request closed without merging**
