### PR TITLE
Remove obsolete physics component

### PR DESCRIPTION
**Pull request by DrSmugleaf**
All of its usages are gone.

### CODE REVIEW

**Comment by metalgearsloth** [comment]
I assume the PR to remove it from the remaining components is coming, otherwise ship it.

**Review by gradientvera — APPROVED** [review]

**Comment by DrSmugleaf** [comment]
> I assume the PR to remove it from the remaining components is coming, otherwise ship it.

It's not used in content either.

**Comment by metalgearsloth** [comment]
> 
> 
> > I assume the PR to remove it from the remaining components is coming, otherwise ship it.
> 
> It's not used in content either.

Orly https://github.com/space-wizards/space-station-14/blob/5127824716d0a2e97acab292df744674073d7a81/Resources/Prototypes/Entities/Constructible/Storage/crate_base.yml#L29

**Comment by DrSmugleaf** [comment]
Nevermind it was used in some YAML prototypes still.

**Pull request merged**
