### PR TITLE
Separate window creation in `OSWindow.Show()` to allow creation in the background

### PR DESCRIPTION
**Pull request by wixoaGit**
OSWindow wouldn't create the window and its UI root until `Show()` was called. This caused issues for controls we needed to initialize & run before ever being visible. Now they are both created immediately, with `Show()` being used to make them visible.

This also required being able to set a window's size after creation, so I added the ability to do that. This is something OpenDream was going to need at some point anyway.

### CODE REVIEW

**Review by Iamgoofball — APPROVED** [review]
░░░░░░░░░░░░▄▄                     
░░░░░░░░░░░█░░█                  
░░░░░░░░░░░█░░█                  
░░░░░░░░░░█░░░█                  
░░░░░░░░░█░░░░█                  
███████▄▄█░░░░░██████▄ 
▓▓▓▓▓▓█░░░░░░░░░░░░░░█ 
▓▓▓▓▓▓█░░░░ PJB, ░░░░░░░█ 
 ▓▓▓▓▓▓█░░░░Add This░░░░█  
▓▓▓▓▓▓█░░░░Please!░░░░░█ 
▓▓▓▓▓▓█░░░░░░░░░░░░░░█ 
▓▓▓▓▓▓█████░░░░░░░░░█   
██████▀░░░░▀▀██████▀

**Review by PJB3005 — COMMENTED** [review]
Definitely not a fan of the breaking changes introduced here. Would it be possible to add a new function instead that creates the window without showing?

**Comment by wixoaGit** [comment]
> Definitely not a fan of the breaking changes introduced here. Would it be possible to add a new function instead that creates the window without showing?

Yea, splitting `Show()` into a `Create()` and `Show()` probably would have been better. I'll redo it like that.

**Comment by wixoaGit** [comment]
The tests are passing on my machine

**Pull request merged**
