### PR TITLE
fix placement grid

### LINKED ISSUE #1891: SnapgridCenter placement doesn't account for viewport size.
image

### LINKED ISSUE #2112: Constructiongrid renders relative to map, not grid
should be relative to grid

### PR DESCRIPTION
**Pull request by PaulRitter**
fixes #2112

placement grid is now relative to the grid.

still breaks when you resize the window, no clue why. @PJB3005 
if we ever get around to fixing that, it will also fix #1891

### CODE REVIEW

**Comment by metalgearsloth** [comment]
> still breaks when you resize the window, no clue why. @PJB3005

Because it doesn't consider viewport size and just does the lines every 32 pixels.

**Comment by PaulRitter** [comment]
> > still breaks when you resize the window, no clue why. @PJB3005
> 
> Because it doesn't consider viewport size and just does the lines every 32 pixels.

b-but i used `EyeManager.PixelsPerMeter` 👉👈

**Review by metalgearsloth — APPROVED** [review]

**Comment by PaulRitter** [comment]
suppose maybe eyemanager.pixelspermeter is just broken then? paging @PJB3005

**Comment by 20kdc** [comment]
I think there's a misunderstanding here of what pixelspermeter is.
pixelspermeter is the "normal", unaltered, amount of pixels per meter (read: tile), assuming that SS14 ran at 1x resolution like a BYOND game would.
So it's a constant 32.
But practically, there are effects like the zoom of an eye that change the relation between this and actual "physical" pixels as used by ScreenToWorld.

**Comment by PJB3005** [comment]
Pixels per meter is the relation of sprite size -> world units. Nothing more.

**Pull request merged**
