### PR TITLE
add CopyData to appearance system

### PR DESCRIPTION
**Pull request by deltanedas**
it copies the apperance of src entity to dest entity yep

needed for prop hunt gaming

### CODE REVIEW

**Comment by PJB3005** [comment]
This isn't nearly enough, many entities use more complex data than just shader parameters that *somehow* needs to be replicated. God knows how.

**Comment by deltanedas** [comment]
current process is:
1. try copying visualizers
2. blacklist if that fails

going good so far

**Comment by metalgearsloth** [comment]
Considering photos would also use this wouldn't you also need to network the spritecomp data too?

**Comment by deltanedas** [comment]
no i just copy it clientside in content :trollface:

**Comment by deltanedas** [comment]
merg

also photos would need a hell of a lot more than AppearanceComponent

**Pull request merged**
