### PR TITLE
Make icons great again

### LINKED ISSUE #1237: Appearance system should skip deleted entities.
It is possible for an entity to be queued for appearance update but then be deleted that same tick, causing a bug such as https://github.com/space-wizards/space-station-14/issues/1777.

### PR DESCRIPTION
**Pull request by metalgearsloth**
* AppearanceComponent checks deleted rather than each visualizer
* Remove the dummy icon entity
* Support for multiple textures in a control (LayeredTextureRect)
* Add support for it to the entity spawner (other areas will need it at some stage e.g. placement manager).

Main purpose is to make iconcomponent not necessary.

### CODE REVIEW

**Comment by DrSmugleaf** [comment]
Fixes https://github.com/space-wizards/RobustToolbox/issues/1237

**Comment by PJB3005** [comment]
Another solution for the icon issue may be to instantiate dummy entities that only have the sprite and visualizers of the entity type in question.

**Comment by metalgearsloth** [comment]
> 
> 
> Another solution for the icon issue may be to instantiate dummy entities that only have the sprite and visualizers of the entity type in question.

It originally had sprites jury rigged but there were a few things breaking when I tried it, I could try again and try to shove stuff through the component manager with it.

**Comment by metalgearsloth** [comment]
@SweptWasTaken for you bb

**Comment by metalgearsloth** [comment]
@PJB3005 can I merge this BB, I enhanced the dummy icon entity, test just seems to be one that fails randomly.

**Pull request merged**
