### PR TITLE
Remove unused IEntityManager parameter from EntityCoordinates.FromMap()

### PR DESCRIPTION
**Pull request by Visne**

### CODE REVIEW

**Comment by gradientvera** [comment]
Did you mean EntityCoordinates?

**Comment by Visne** [comment]
> 
> 
> Did you mean EntityCoordinates?

Yes, I scrolled to the top of the file without looking.

**Review by PJB3005 — CHANGES_REQUESTED** [review]
Make a new overload instead and obsolete the old one so we don't have to do a submodule update dance.

**Comment by Visne** [comment]
> 
> 
> Make a new overload instead and obsolete the old one so we don't have to do a submodule update dance.

Done.

**Review by PJB3005 — APPROVED** [review]

**Pull request merged**
