### PR TITLE
Merge SFML into master

### PR DESCRIPTION
**Pull request by ZoldorfTheWizard**

### CODE REVIEW

**Comment by YotaXP** [comment]
Hey @Silvertorch5, sorry we never got around to this.  Is it still good to merge?
Also, what does this do about that one PR that was pulled to 'master'?  IIRC, it didn't need to be on 'sfml'. #26

**Comment by ZoldorfTheWizard** [comment]
no, my current devops branch has my latest stuff

As for that pr, dimitri just added basic sfml viewport stuff, I modified it slightly in devops

**Comment by PJB3005** [comment]
Are you sure about that? http://i.imgur.com/JinHpuo.png

**Comment by ZoldorfTheWizard** [comment]
yep, I haven't pushed anything in a while

**Comment by PJB3005** [comment]
Ah, alright.

**Pull request closed without merging**
